//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayServiceConsoleConsumer.DayOfWeekService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DayOfWeekService.IGetDayOfWeek")]
    public interface IGetDayOfWeek {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDayOfWeek/DayOfWeekInBulgarian", ReplyAction="http://tempuri.org/IGetDayOfWeek/DayOfWeekInBulgarianResponse")]
        string DayOfWeekInBulgarian(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDayOfWeek/DayOfWeekInBulgarian", ReplyAction="http://tempuri.org/IGetDayOfWeek/DayOfWeekInBulgarianResponse")]
        System.Threading.Tasks.Task<string> DayOfWeekInBulgarianAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetDayOfWeekChannel : DayServiceConsoleConsumer.DayOfWeekService.IGetDayOfWeek, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDayOfWeekClient : System.ServiceModel.ClientBase<DayServiceConsoleConsumer.DayOfWeekService.IGetDayOfWeek>, DayServiceConsoleConsumer.DayOfWeekService.IGetDayOfWeek {
        
        public GetDayOfWeekClient() {
        }
        
        public GetDayOfWeekClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetDayOfWeekClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDayOfWeekClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDayOfWeekClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DayOfWeekInBulgarian(System.DateTime date) {
            return base.Channel.DayOfWeekInBulgarian(date);
        }
        
        public System.Threading.Tasks.Task<string> DayOfWeekInBulgarianAsync(System.DateTime date) {
            return base.Channel.DayOfWeekInBulgarianAsync(date);
        }
    }
}
