//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IStringCompare")]
public interface IStringCompare
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringCompare/NumberOfContains", ReplyAction="http://tempuri.org/IStringCompare/NumberOfContainsResponse")]
    int NumberOfContains(string first, string second);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringCompare/NumberOfContains", ReplyAction="http://tempuri.org/IStringCompare/NumberOfContainsResponse")]
    System.Threading.Tasks.Task<int> NumberOfContainsAsync(string first, string second);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IStringCompareChannel : IStringCompare, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class StringCompareClient : System.ServiceModel.ClientBase<IStringCompare>, IStringCompare
{
    
    public StringCompareClient()
    {
    }
    
    public StringCompareClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public StringCompareClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StringCompareClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StringCompareClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int NumberOfContains(string first, string second)
    {
        return base.Channel.NumberOfContains(first, second);
    }
    
    public System.Threading.Tasks.Task<int> NumberOfContainsAsync(string first, string second)
    {
        return base.Channel.NumberOfContainsAsync(first, second);
    }
}
